### PR TITLE
update wp and plugins - add code for local db

### PR DESCRIPTION
**Pull request by stephdavid**
update wp and plugins, added the changed Make File and bin file for installing the prod site database on a local build

### CODE REVIEW

**Review by RobLoweMOJ — COMMENTED** [review]
Hi @stephdavid ,

I can't see the local-db-import.sh file in the bin directory. It may need to be added.

You can get a copy of it from victcomm repo.

Thanks,

Rob

**Comment by stephdavid** [comment]
Ooops. My bad.

**Review by RobLoweMOJ — APPROVED** [review]
Looks good. Please check this on the dev server to double check the updated plugins are working as expected.

**Comment by RobLoweMOJ** [comment]
Merging to push to Dev

**Pull request merged**
